param(
    [Parameter(Mandatory = $true)]
    [string]$OutputPath,

    [string]$DisplayVersionOverride = "",

    [string]$AssemblyVersionOverride = ""
)

$ErrorActionPreference = "Stop"

function Invoke-Git {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$Args)
    $previous = $ErrorActionPreference
    $ErrorActionPreference = "SilentlyContinue"
    try {
        $output = & git @Args 2>$null
        return @{
            ExitCode = $LASTEXITCODE
            Output = if ($output) { [string]$output } else { "" }
        }
    }
    finally {
        $ErrorActionPreference = $previous
    }
}

function Normalize-Tag([string]$Tag) {
    return ($Tag.Trim() -replace '^v\.?', '')
}

function ConvertTo-AssemblyVersion([string]$Numeric) {
    $numbers = New-Object System.Collections.Generic.List[int]
    foreach ($part in $Numeric.Split('.')) {
        $digits = ($part -replace '[^0-9].*$', '')
        if ($digits -match '^\d+$') {
            [void]$numbers.Add([int]$digits)
        }
    }

    while ($numbers.Count -lt 4) {
        [void]$numbers.Add(0)
    }

    if ($numbers.Count -gt 4) {
        $numbers = $numbers.GetRange(0, 4)
    }

    return ($numbers -join '.')
}

function Escape-CSharpString([string]$Value) {
    return $Value.Replace('\', '\\').Replace('"', '\"')
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$isTaggedRelease = $false
$numeric = "0.0.0"
$sha = "unknown"

Push-Location $repoRoot
try {
    $shaResult = Invoke-Git rev-parse --short HEAD
    if ($shaResult.ExitCode -ne 0 -or [string]::IsNullOrWhiteSpace($shaResult.Output)) {
        throw "git rev-parse --short HEAD failed."
    }

    $sha = $shaResult.Output.Trim()

    if (-not [string]::IsNullOrWhiteSpace($DisplayVersionOverride)) {
        $numeric = Normalize-Tag $DisplayVersionOverride.Trim()
        $isTaggedRelease = $true
    }
    else {
        $exactTagResult = Invoke-Git describe --tags --exact-match
        if ($exactTagResult.ExitCode -eq 0 -and -not [string]::IsNullOrWhiteSpace($exactTagResult.Output)) {
            $numeric = Normalize-Tag $exactTagResult.Output
            $isTaggedRelease = $true
        }
        else {
            $nearestTagResult = Invoke-Git describe --tags --abbrev=0
            if ($nearestTagResult.ExitCode -eq 0 -and -not [string]::IsNullOrWhiteSpace($nearestTagResult.Output)) {
                $numeric = Normalize-Tag $nearestTagResult.Output
            }

            $isTaggedRelease = $false
        }
    }
}
finally {
    Pop-Location
}

$display = "$numeric ($sha)"
$informational = "$numeric+$sha"

if ([string]::IsNullOrWhiteSpace($AssemblyVersionOverride)) {
    $assembly = ConvertTo-AssemblyVersion $numeric
}
else {
    $assembly = $AssemblyVersionOverride.Trim()
}

$displayEscaped = Escape-CSharpString $display
$numericEscaped = Escape-CSharpString $numeric
$shaEscaped = Escape-CSharpString $sha
$informationalEscaped = Escape-CSharpString $informational
$assemblyEscaped = Escape-CSharpString $assembly
$fromTagLiteral = if ($isTaggedRelease) { "true" } else { "false" }

$content = @"
// <auto-generated /> Do not edit - generated by ci/resolve-build-version.ps1
using System.Reflection;

[assembly: AssemblyVersion("$assemblyEscaped")]
[assembly: AssemblyFileVersion("$assemblyEscaped")]
[assembly: AssemblyInformationalVersion("$informationalEscaped")]

namespace HeartopiaMod
{
    internal static class ModBuildVersion
    {
        /// <summary>Human-readable version for UI (e.g. 1.8.0 (4a31f61)).</summary>
        public const string Display = "$displayEscaped";

        /// <summary>SemVer core for BepInEx/MelonLoader metadata (e.g. 1.8.0).</summary>
        public const string Numeric = "$numericEscaped";

        public const string Sha = "$shaEscaped";

        /// <summary>SemVer with build metadata for assembly info (e.g. 1.8.0+4a31f61).</summary>
        public const string Informational = "$informationalEscaped";
        public const bool IsTaggedRelease = $fromTagLiteral;
    }
}
"@

$outputDirectory = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($outputDirectory) -and -not (Test-Path $outputDirectory)) {
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutputPath, $content, $utf8NoBom)
Write-Host "Mod version: $display (assembly $assembly, tagged=$isTaggedRelease)"
